import { FLUENT_3D } from "./constants";

export const ICON_3D_URLS = {
  dashboard: `${FLUENT_3D}/Bar%20chart/3D/bar_chart_3d.png`,
  question: `${FLUENT_3D}/Red%20question%20mark/3D/red_question_mark_3d.png`,
  clipboard: `${FLUENT_3D}/Clipboard/3D/clipboard_3d.png`,
  users: `${FLUENT_3D}/Busts%20in%20silhouette/3D/busts_in_silhouette_3d.png`,
  trophy: `${FLUENT_3D}/Trophy/3D/trophy_3d.png`,
  key: `${FLUENT_3D}/Key/3D/key_3d.png`,
  shield: `${FLUENT_3D}/Shield/3D/shield_3d.png`,
  gear: `${FLUENT_3D}/Gear/3D/gear_3d.png`,
  door: `${FLUENT_3D}/Door/3D/door_3d.png`,
  chart: `${FLUENT_3D}/Bar%20chart/3D/bar_chart_3d.png`,
  trending: `${FLUENT_3D}/Chart%20increasing/3D/chart_increasing_3d.png`,
  clock: `${FLUENT_3D}/Alarm%20clock/3D/alarm_clock_3d.png`,
  document: `${FLUENT_3D}/Page%20facing%20up/3D/page_facing_up_3d.png`,
  warning: `${FLUENT_3D}/Warning/3D/warning_3d.png`,
  book: `${FLUENT_3D}/Open%20book/3D/open_book_3d.png`,
  target: `${FLUENT_3D}/Bullseye/3D/bullseye_3d.png`,
  medal: `${FLUENT_3D}/Sports%20medal/3D/sports_medal_3d.png`,
  person: `${FLUENT_3D}/Bust%20in%20silhouette/3D/bust_in_silhouette_3d.png`,
  award: `${FLUENT_3D}/1st%20place%20medal/3D/1st_place_medal_3d.png`,
  send: `${FLUENT_3D}/Envelope/3D/envelope_3d.png`,
  pin: `${FLUENT_3D}/Round%20pushpin/3D/round_pushpin_3d.png`,
  phone: `${FLUENT_3D}/Telephone/3D/telephone_3d.png`,
  crown: `${FLUENT_3D}/Crown/3D/crown_3d.png`,
  graduation: `${FLUENT_3D}/Graduation%20cap/3D/graduation_cap_3d.png`,
  star: `${FLUENT_3D}/Glowing%20star/3D/glowing_star_3d.png`,
  calendar: `${FLUENT_3D}/Calendar/3D/calendar_3d.png`,
  building: `${FLUENT_3D}/Office%20building/3D/office_building_3d.png`,
  sparkles: `${FLUENT_3D}/Sparkles/3D/sparkles_3d.png`,
  calculator: `${FLUENT_3D}/Abacus/3D/abacus_3d.png`,
  monitor: `${FLUENT_3D}/Laptop/3D/laptop_3d.png`,
  globe: `${FLUENT_3D}/Globe%20with%20meridians/3D/globe_with_meridians_3d.png`,
  dna: `${FLUENT_3D}/Dna/3D/dna_3d.png`,
  books: `${FLUENT_3D}/Books/3D/books_3d.png`,
  running: `${FLUENT_3D}/Person%20running/Default/3D/person_running_3d_default.png`,
  laptop: `${FLUENT_3D}/Laptop/3D/laptop_3d.png`,
  smartphone: `${FLUENT_3D}/Mobile%20phone/3D/mobile_phone_3d.png`,
  logout: `${FLUENT_3D}/Door/3D/door_3d.png`,
} as const;

export type IconName = keyof typeof ICON_3D_URLS;
